# Generated by Django 2.2.3 on 2019-07-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190717_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='favorited_by',
        ),
    ]
