# Generated by Django 2.2.3 on 2019-07-17 19:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20190717_1517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Otter',
            new_name='OtterProfile',
        ),
    ]
