# Generated by Django 2.2.3 on 2019-07-17 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190717_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otterprofile',
            name='username',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
