# Generated by Django 2.2.3 on 2019-07-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190717_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='otterprofile',
            name='avatar',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otterprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us a bit about yourself!', max_length=500),
        ),
    ]
