# Generated by Django 2.2.3 on 2019-07-18 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190717_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
